In [1]:
import pandas as pd
data = pd.Series([10,20,30,40])  
print(data)

0    10
1    20
2    30
3    40
dtype: int64

In [2]:
data = pd.Series([10,20,30],index=["x","y","z"])
print(data)

x    10
y    20
z    30
dtype: int64

In [3]:
data = {
    "Name": ["Ram", "Vani"],
    "Age": [20,25 ]
}

df = pd.DataFrame(data)
print(df)
print("\n")


print(df.loc[0])

   Name  Age
0   Ram   20
1  Vani   25


Name    Ram
Age      20
Name: 0, dtype: object

In [6]:
df=pd.read_csv("C:\\Users\\RVUW276\\Downloads\\Untitled spreadsheet - Sheet1.csv")
print(df)

      Name  Age
0  Nithish   18
1   Yashas   20
2   Mithun   18

In [7]:
df.isnull()

    Name    Age
0  False  False
1  False  False
2  False  False

In [8]:
df.dropna()

      Name  Age
0  Nithish   18
1   Yashas   20
2   Mithun   18